import type { Metadata } from "next";
import { roboto, merriweather } from "@/lib/fonts";
import "@/styles/globals.css";
import { Footer } from "@/components/footer";
import { Header } from "@/components/header";
import { Toaster } from "@/components/ui/toaster";
import { getSession } from "@/lib/auth";
import UserContextProvider from "@/components/session-context";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getSession();

  return (
    <UserContextProvider session={session}>
      <html lang="en">
        <body className={`${roboto.className} overflow-x-hidden`}>
          <Header />
          {children}
          <Toaster />
          <Footer />
        </body>
      </html>
    </UserContextProvider>
  );
}
